{% set name = "plum-py" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-py-{{ version }}.tar.gz
  sha256: f0054734c2e91146c43b9f4205e0d73b9a554f8f978812439e3f3f10bd019c11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=39.0.1
  run:
    - python >=3.6

test:
  imports:
    - plum
    - plum.bitfields
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plum-py.readthedocs.io/en/latest/index.html
  summary: Pack/Unpack Memory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
