{% set name = "plum-py" %}
{% set version = "0.7.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-py-{{ version }}.tar.gz
  sha256: 3bdfaa8feee07745447f833235c57d02cb6c599a0b5cc4b10a10c7b024b54555

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=39.0.1
  run:
    - python >=3.6

test:
  imports:
    - plum
    - plum.bitfields
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plum-py.readthedocs.io/en/latest/index.html
  summary: Pack/Unpack Memory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
